export enum EmploymentType {
  DINOMINATIONAL = 'DINOMINATIONAL',

  INSTITUTIONAL = 'INSTITUTIONAL',

  STATUTORY = 'STATUTORY',

  CONTRACTUAL = 'CONTRACTUAL',

  PROBATIONARY = 'PROBATIONARY',

  TRAINEE = 'TRAINEE',

  AGENCY = 'AGENCY',
}
